// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Animation: typeof import('./src/components/Animation.vue')['default']
    BaseInput: typeof import('./src/components/BaseInput.vue')['default']
    Box: typeof import('./src/components/svg/Box.svg')['default']
    ContainerBox: typeof import('./src/components/svg/ContainerBox.svg')['default']
    ContainerDoorLeft: typeof import('./src/components/svg/ContainerDoorLeft.svg')['default']
    ContainerDoorRight: typeof import('./src/components/svg/ContainerDoorRight.svg')['default']
    ContainerLock: typeof import('./src/components/svg/ContainerLock.svg')['default']
    Diamond: typeof import('./src/components/svg/Diamond.svg')['default']
    DiamondInShowcase: typeof import('./src/components/svg/DiamondInShowcase.svg')['default']
    PasswordBg: typeof import('./src/components/svg/PasswordBg.svg')['default']
    Safe: typeof import('./src/components/svg/Safe.svg')['default']
    SafeVault: typeof import('./src/components/svg/SafeVault.svg')['default']
    Shiny: typeof import('./src/components/svg/Shiny.svg')['default']
    Showcase: typeof import('./src/components/svg/Showcase.svg')['default']
  }
}

export { }
